// Copyright (c) 2026 Lark Technologies Pte. Ltd.
// SPDX-License-Identifier: MIT

package plugin_e2e

import (
	"bytes"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"testing"
	"time"
)

const shutdownSignalPlugin = `// Code generated by plugin_e2e; DO NOT EDIT.
package plugin

import (
	"context"
	"errors"
	"os"
	"time"

	"github.com/larksuite/cli/extension/platform"
)

func init() {
	platform.Register(
		platform.NewPlugin("shutdown-signal", "0.1.0").
			Wrap("wait", platform.All(), func(platform.Handler) platform.Handler {
				return func(ctx context.Context, _ platform.Invocation) error {
					if err := os.WriteFile(os.Getenv("LARK_CLI_READY_MARKER"), []byte("ready"), 0o600); err != nil {
						return err
					}
					select {
					case <-ctx.Done():
						return ctx.Err()
					case <-time.After(30 * time.Second):
						return errors.New("command context was not canceled")
					}
				}
			}).
			On(platform.Shutdown, "record", func(context.Context, *platform.LifecycleContext) error {
				marker := os.Getenv("LARK_CLI_SHUTDOWN_MARKER")
				if marker == "" {
					return errors.New("LARK_CLI_SHUTDOWN_MARKER is empty")
				}
				return os.WriteFile(marker, []byte("shutdown"), 0o600)
			}).
			FailOpen().
			MustBuild())
}
`

func TestSIGINTRunsShutdownHookAndReturns130(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("os.Interrupt cannot be sent to Windows processes")
	}

	bin := buildFork(t, "shutdown-signal", shutdownSignalPlugin)
	markerDir := t.TempDir()
	readyMarker := filepath.Join(markerDir, "ready")
	shutdownMarker := filepath.Join(markerDir, "shutdown")

	cmd := exec.Command(bin, "schema")
	cmd.Env = append(isolatedEnv(t),
		"LARK_CLI_READY_MARKER="+readyMarker,
		"LARK_CLI_SHUTDOWN_MARKER="+shutdownMarker,
	)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Start(); err != nil {
		t.Fatalf("start fork: %v", err)
	}
	t.Cleanup(func() {
		if cmd.ProcessState == nil {
			_ = cmd.Process.Kill()
			_ = cmd.Wait()
		}
	})

	waitForMarker(t, readyMarker, 10*time.Second)
	if err := cmd.Process.Signal(os.Interrupt); err != nil {
		t.Fatalf("send SIGINT: %v", err)
	}

	waitCh := make(chan error, 1)
	go func() { waitCh <- cmd.Wait() }()
	var waitErr error
	select {
	case waitErr = <-waitCh:
	case <-time.After(10 * time.Second):
		_ = cmd.Process.Kill()
		t.Fatalf("fork did not exit after SIGINT; stdout=%s stderr=%s", stdout.String(), stderr.String())
	}

	var exitErr *exec.ExitError
	if !errors.As(waitErr, &exitErr) || exitErr.ExitCode() != 130 {
		t.Fatalf("SIGINT exit error = %v, exit code = %d, want 130; stdout=%s stderr=%s",
			waitErr, cmd.ProcessState.ExitCode(), stdout.String(), stderr.String())
	}
	if data, err := os.ReadFile(shutdownMarker); err != nil || string(data) != "shutdown" {
		t.Fatalf("Shutdown marker = %q, err=%v, want shutdown", data, err)
	}
}

func waitForMarker(t *testing.T, path string, timeout time.Duration) {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if _, err := os.Stat(path); err == nil {
			return
		}
		time.Sleep(10 * time.Millisecond)
	}
	t.Fatalf("marker %s was not created within %s", path, timeout)
}
